- name: Install bind9
  ansible.builtin.apt:
    update-cache: yes
    pkg:
      - bind9
      - rsync

- name: We have a config to copy in
  stat:
    path: /things/homelab/dns/etc-bind/named.conf
  register: bind_config

- name: Install /etc/bind
  ansible.posix.synchronize:
    src: /things/homelab/dns/etc-bind/
    dest: /etc/bind/
    checksum: true
    recursive: true
    delete: true
  when: bind_config.stat.exists
  register: bind_conf_update

- name: Reload bind if we've updated the config.
  ansible.builtin.systemd:
    name: bind9.service
    state: restarted
  when: bind_conf_update.changed
