# --- Hashicorp apt repo setup ---

- name: Add Hashicorp apt signing key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add Hashicorp apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ download_arch }}] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp
    update_cache: yes

# --- Consul ---

- name: Install consul at pinned version
  ansible.builtin.apt:
    name: "consul={{ consul_version }}-1"
    state: present

- name: Hold consul package at current version
  ansible.builtin.dpkg_selections:
    name: consul
    selection: hold

- name: Create consul user
  ansible.builtin.user:
    name: consul
    create_home: no
    home: /etc/consul.d
    shell: /bin/false

- name: Create /opt/consul
  ansible.builtin.file:
    path: '/opt/consul'
    state: directory
    owner: consul
    group: consul

- name: Create /etc/consul.d
  ansible.builtin.file:
    path: '/etc/consul.d'
    mode: '700'
    state: directory
    owner: consul
    group: consul

- name: Generate consul.hcl
  ansible.builtin.template:
    src: consul.hcl.j2
    dest: '/etc/consul.d/consul.hcl'
    owner: consul
    group: consul
  notify: Restart consul

- name: Generate server.hcl
  ansible.builtin.template:
    src: server.hcl.j2
    dest: '/etc/consul.d/server.hcl'
    owner: consul
    group: consul
  notify: Restart consul

- name: Enable consul on boot
  ansible.builtin.systemd:
    name: consul
    enabled: yes
    state: started
  when: consul_enabled

# --- Nomad ---

- name: Install nomad at pinned version
  ansible.builtin.apt:
    name: "nomad={{ nomad_version }}-1"
    state: present

- name: Hold nomad package at current version
  ansible.builtin.dpkg_selections:
    name: nomad
    selection: hold

- name: Create /opt/nomad
  ansible.builtin.file:
    path: '/opt/nomad'
    state: directory

- name: Create /local
  ansible.builtin.file:
    path: '/local'
    state: directory

- name: Create /etc/nomad.d
  ansible.builtin.file:
    path: '/etc/nomad.d'
    mode: '700'
    state: directory

- name: Copy nomad.hcl
  ansible.builtin.copy:
    src: nomad.hcl
    dest: '/etc/nomad.d/'
  notify: Restart nomad

- name: Copy server.hcl
  ansible.builtin.copy:
    src: server.hcl
    dest: '/etc/nomad.d/'
  when: nomad_server
  notify: Restart nomad

- name: Copy client.hcl
  ansible.builtin.copy:
    src: client.hcl
    dest: '/etc/nomad.d/'
  notify: Restart nomad

- name: Enable nomad on boot
  ansible.builtin.systemd:
    name: nomad
    enabled: yes
    state: started
