apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: cringesweeper
  name: cringesweeper
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cringesweeper
  name: cringesweeper
  namespace: cringesweeper
spec:
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 8080
  selector:
    app: cringesweeper
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cringesweeper-servicemonitor
  namespace: monitoring 
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: cringesweeper
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
