- name: Add the gcloud apt key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg
    state: present

- name: Add the gcloud apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    state: present

- name: Packages for a web server
  ansible.builtin.apt:
    update-cache: yes
    pkg:
      - cron
      - nginx
      - python3-certbot
      - python3-certbot-nginx
      - google-cloud-cli


- name: install SH nginx config
  ansible.builtin.copy:
    src: www.strategichopes.co.conf
    dest: /etc/nginx/sites-enabled/www.strategichopes.co.conf
  register: sh_nginx

- name: reload nginx for new config (strategichopes.co)
  ansible.builtin.systemd:
    name: nginx.service
    state: restarted
  when: sh_nginx.changed

- name: certbot renew cron job
  ansible.builtin.cron:
    name: "certbot renew"
    special_time: "weekly"
    user: root
    job: "certbot renew"
