- name: Install prometheus-node-exporter
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - prometheus-node-exporter

- name: Enable and start prometheus-node-exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    enabled: yes
    state: started
