global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "blackbox_alerting_rules.yml"
  - "node_exporter_recording_rules.yml"
  - "node_exporter_alerting_rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node_exporter
    scrape_interval: 1m
    scrape_timeout: 1m
    metrics_path: "/metrics"
    static_configs:
      - targets: ['hedwig:9100', 'rabbitseason:9100', 'duckseason:9100', 'picluster1:9100', 'picluster2:9100', 'picluster3:9100', 'picluster4:9100', 'picluster5:9100', 'tings:9100']
  - job_name: consul
    scrape_interval: 1m
    scrape_timeout: 1m
    metrics_path: "/metrics"
    static_configs:
      - targets: ['prom-consul-exporter.service.consul:9107']

  - job_name: blackbox
    static_configs:
      - targets: ['prom-blackbox-exporter.service.home.consul:9115']

  - job_name: blackbox-http-base
    metrics_path: "/probe"
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - 192.168.100.250
        - 192.168.100.251
        - 192.168.100.253
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prom-blackbox-exporter.service.home.consul:9115

  - job_name: blackbox-ping
    metrics_path: "/probe"
    params:
      module: [icmp]
    scrape_interval: 1m
    static_configs:
      - targets:
        - picluster1
        - picluster2
        - picluster3
        - picluster4
        - picluster5
        - hedwig
        - rabbitseason
        - duckseason
        - tings
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prom-blackbox-exporter.service.home.consul:9115

  - job_name: blackbox-dns
    scrape_interval: 5s
    metrics_path: /probe
    static_configs:
      - targets:
        - home.andvari.net:192.168.100.250
        - home.andvari.net:192.168.100.251
        - home.andvari.net:192.168.100.253
        - docker-registry.service.consul:192.168.100.250
        - docker-registry.service.consul:192.168.100.251
        - docker-registry.service.consul:192.168.100.253
        - nomad-dns-exporter.service.nomad:192.168.100.250
        - nomad-dns-exporter.service.nomad:192.168.100.251
        - nomad-dns-exporter.service.nomad:192.168.100.253
    relabel_configs:
    - source_labels: [__address__]
      regex: (.*):.*$
      replacement: $1
      target_label: domain
    - source_labels: [__address__]
      regex: .*:(.*)$
      replacement: $1
      target_label: instance
    - source_labels: [domain]
      target_label: __param_module
    - source_labels: [instance]
      target_label: __param_target
    - target_label: __address__
      replacement: prom-blackbox-exporter.service.home.consul:9115


alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - prom-alertmanager.service.home.consul:9093

