global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "blackbox_alerting_rules.yml"
  - "node_exporter_recording_rules.yml"
  - "node_exporter_alerting_rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node_exporter
    scrape_interval: 1m
    scrape_timeout: 1m
    metrics_path: "/metrics"
    static_configs:
      - targets: ['hedwig:9100', 'rabbitseason:9100', 'duckseason:9100', 'donkeh:9100', 'picluster5:9100', 'tings:9100']
  - job_name: consul
    scrape_interval: 1m
    scrape_timeout: 1m
    metrics_path: "/metrics"
    static_configs:
      - targets: ['prom-consul-exporter.home.nomad.andvari.net:9107']

  - job_name: nomad-dns-exporter
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ['hedwig:5334', 'rabbitseason:5334', 'duckseason:5334', 'donkeh:5334']

  - job_name: nut2mqtt
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ['nut2mqtt.home.nomad.andvari.net:3494']


  - job_name: blackbox
    static_configs:
      - targets: ['prom-blackbox-exporter.home.nomad.andvari.net:9115']

  - job_name: blackbox-http-base
    metrics_path: "/probe"
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - home.andvari.net
        - www.sica.ie
        - www.strategichopes.co
        - www.andvari.net
        - log.andvari.net
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prom-blackbox-exporter.home.nomad.andvari.net:9115

  - job_name: blackbox-ping
    metrics_path: "/probe"
    params:
      module: [icmp]
    scrape_interval: 1m
    static_configs:
      - targets:
        - picluster5
        - hedwig
        - rabbitseason
        - duckseason
        - donkeh
        - tings
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prom-blackbox-exporter.home.nomad.andvari.net:9115

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - prom-alertmanager.home.nomad.andvari.net:9093

