global:
  smtp_smarthost: 'smtp:25'
  smtp_from: 'alerts@mail.andvari.net'


route:
  receiver: filtered
  repeat_interval: 3h

  routes:
  - match:
      severity: critical
    receiver: priority

  - match:
      severity: warning
    receiver: filtered

receivers:
  - name: filtered
    email_configs:
    - to: 'alerts@mail.andvari.net'
      require_tls: false
  - name: priority 
    email_configs:
    - to: 'doc@gerrup.eu'
      require_tls: false

