- name: Create mountpoint /things
  ansible.builtin.file:
    path: '/things'
    state: directory

- name: Mount NFS share {{ nfs_primary }}:{{ nfs_share }} on /things
  ansible.posix.mount:
    path: /things
    src: "{{ nfs_primary }}:{{ nfs_share }}"
    opts: nofail,noatime,nolock,intr,tcp
    fstype: nfs
    boot: true
    state: mounted
