nfs_server:
        hosts:
                duckseason:
        vars:
                nfs_server_exports:
                        - export:
                          access:
                                  - hostname: '192.168.100.240/28'
                                    options:
                                        - 'rw'
                                        - 'sync'
                                        - 'no_subtree_check'
                                  - hostname: 'localhost'
                                    options:
                                        - 'rw'
                                        - 'sync'
                                        - 'no_subtree_check'
                          path: /export/things

login:
        hosts:
                rabbitseason:
                        ansible_user: doc

nomadconsul:
        hosts:
                picluster2:
                picluster4:
                picluster5:
                        nomad_server: false
                        consul_enabled: false
                duckseason:
                        download_arch: amd64
                        ansible_user: doc
                        nfs_primary: localhost
                hedwig:
                        download_arch: amd64
                        ansible_user: doc
        vars:
                download_arch: arm64
                ansible_user: pi
                consul_gossip_key: "{{ lookup('env', 'CONSUL_GOSSIP_KEY') }}"
                existing_consul_server: 192.168.100.250 # hedwig
                nomad_server: true
                consul_enabled: true
                # nfs_primary and nfs_share define where /things is (it's at nfs_primary:nfs_share)
                # If you update this, remember to set nfs_primary to localhost for that host only, above.
                nfs_primary: duckseason
                nfs_share: "/export/things"
                docker_registry_proxy: https://docker-registry.home.andvari.net:5001

k8s:
        hosts:
                bebop:
                rocksteady:
                donkeh:
        vars:
                # for docker, etc.
                download_arch: amd64
                ansible_user: doc
                # nfs_primary and nfs_share define where /things is (it's at nfs_primary:nfs_share)
                # If you update this, remember to set nfs_primary to localhost for that host only, above.
                nfs_primary: duckseason
                nfs_share: "/export/things"

# Machines with a localy connected UPS.
ups:
        hosts:
                hedwig:
                        ups_name: eaton5s
                duckseason:
                        ups_name: eaton5p
        vars:
                ups_vendor_id: '0463'
                ups_pollfreq: 30

