linux_aptlike:
        hosts:
                lucien.andvari.net:
                        ansible_user: doc
publicweb:
        hosts:
                copernicus.andvari.net:
                        ansible_user: doc
publicsmtp:
        hosts:
                hooty.andvari.net:
                        smtp_hostname: hooty
                        ansible_user: ubuntu
                        enable_mailman: true

