linux_aptlike:
        hosts:
                lucien.andvari.net:
                        ansible_user: doc
publicweb:
        hosts:
                copernicus.andvari.net:
                        ansible_user: doc
publicsmtp:
        hosts:
                copernicus.andvari.net:
                        smtp_hostname: copernicus
                        ansible_user: doc

