- name: nomad/consul nodes
  hosts: nomadconsul
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - nfs_client
    - nomad
    - consul

- name: k8s hosts
  hosts: k8s
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - nfs_client
    - k8s

- name: nfs servers
  hosts: nfs_server
  become: true
  become_user: root
  roles:
    - role: ansible-nfs-server

- name: dns servers
  hosts: dns_server
  become: true
  become_user: root
  roles:
    - role: dns_server
