- name: nomad/consul nodes
  hosts: nomadconsul
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - hashicorp

- name: nfs servers
  hosts: nfs_server
  become: true
  become_user: root
  roles:
    - role: ansible-nfs-server
    - role: nfs_server

- name: dns servers
  hosts: dns_server
  become: true
  become_user: root
  roles:
    - role: dns_server

- name: login servers
  hosts: login
  become: true
  become_user: root
  roles:
    - role: login

- name: UPS machines
  hosts: ups
  become: true
  become_user: root
  roles:
    - role: ups

- name: docker hosts (non-nomad)
  hosts: docker
  become: true
  become_user: root
  roles:
    - role: docker

- name: all physical hosts
  hosts: node_exporter
  any_errors_fatal: false
  become: true
  become_user: root
  roles:
    - role: node_exporter
