name: test-haproxy-config
run-name: haproxy.cfg OK
on:
  push:
    paths:
      - 'nomad/infra/web/haproxy.cfg'
jobs:
  haproxy-config-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 
        uses: actions/checkout@v3
      - name: Run docker test.
        uses: addnab/docker-run-action@v3
        with:
          image: haproxy:2.7
          options: |
            -v ${{ github.workspace }}/nomad/infra/web/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
          run: haproxy -f /usr/local/etc/haproxy/haproxy.cfg -c
