name: test-nginx-config
run-name: see if nginx config is valid
on: [push]
jobs:
  nginx-config-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 
        uses: actions/checkout@v3
      - name: Run docker test.
        uses: addnab/docker-run-action@v3
        with:
          image: nginx:latest
          options: |
            -v ${{ github.workspace }}/cicd/nginx-local-check/local-haproxy-upstreams.conf:/local/local-haproxy-upstreams.conf:ro
            -v ${{ github.workspace }}/nomad/infra/web/default.conf:/etc/nginx/conf.d/default.conf:ro
          run: nginx -c /etc/nginx/nginx.conf
